<template>
  <div id="app" class="pattern-bg">

    <div id="header">
      <span class="bookend">⊰⟆</span>
      <span class="center">Syd Strzempko</span>
      <span class="bookend">⟅⊱</span>
    </div>

    <div id="main">
      <div id="nav">
          <router-link to="/">home</router-link>
          <router-link to="/work">work</router-link>
          <router-link to="/art">art</router-link>
      </div>
      <Route :name="this.$route.name" />
    </div>

    <div id="footer">
      <a href="https://github.com/syd-strzempko">©2022 Syd Strzempko</a>
    </div>

  </div>
</template>

<script>
import Route from '@/components/Route.vue'

export default {
  name: 'App',
  components: {
    Route
  }
}
</script>

<style>

@font-face {
  font-family: "AlbertusMT";
  src: local("AlbertusMT"),
   url(./fonts/AlbertusMT/AlbertusMT.otf) format("opentype");
}
@import url('https://fonts.googleapis.com/css2?family=PT+Sans&family=PT+Serif&display=swap');

:root {
  --gold: #FBB829;
  --gold2: #A77A1B; /* Autogenerated with groove border */
  --bright: #9ED300; /* Lime green */
  --gr1: #375625;
  --gr2: #2E4F20;
  --gr3: #233D17;
  --bl1: #2c3e50; /* Dark slate blue */
  --dark: #224840; /* Dark bluish green */
}

html, body, #app { 
  height: 100%;
  margin: 0;
}

#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  font-family: "PT Serif", Arial, sans-serif;
  background-color: var(--dark);
  display: flex;
  flex-flow: column;
  justify-content: space-between;
}

#header {
  background-color: var(--dark);
  border: .5rem groove var(--gold);
  border-radius: 5px;
  font-family: "AlbertusMT";
  line-height: 3rem;
}
#header .center {
  font-size: 2.5rem;
  color: white;
  padding: 0.25rem 0.5rem;
}

#footer {
  background-color: var(--dark);
}
#footer a {
  font-weight: normal;
  color: white;
}

/**********************

TODO:
- SSL certify
- tile view of work on larger browsers?
- change tile view on mobile for art?

*******************/

#main {
  display: flex;
  flex-flow: column nowrap;
  align-items: stretch;
  justify-content: center;
}

/* Nav Bar */
#nav {
  display: flex;
  flex-flow: row;
  padding: .5rem 0 0 .5rem;
}
#nav a {
  padding: .25rem;
  font-weight: bold;
  color: #2c3e50;
  text-decoration: none;
  background-color: grey;
  border: .25rem solid var(--gold2);
  border-radius: 5px;
  margin-bottom: -0.6rem;
}
#nav a.router-link-exact-active {
  color: var(--bright);
  background-color: white;
  /* To overlap #content border */
  border: .25rem solid var(--gold);
  border-bottom: 0.5rem solid white;
  margin-bottom: -0.6rem;
  z-index: 5;
}

.content {
  border: .5rem groove var(--gold);
  background-color: white;
  padding: .25rem 1rem .5rem;
}

/* Misc. */
.viewDesktop {
  display: none !important;
}

.bookend, .iconlink {
  vertical-align: text-bottom;
  color: var(--gold);
  font-size: 1.75rem;
}
.iconlink:hover {

  color: var(--bright);
}

ul {
  text-align: justify;
  list-style-type: square;
}
a {
  text-decoration: none;
  font-weight: bold;
  color: var(--dark);
}
a:hover, a:hover * {
  color: var(--bright);
}
h1, h2 {
  margin: .5rem;
  font-family: "AlbertusMT";
  color: var(--gr1);
}
h2 {
  color: var(--gr2);
}

.pattern-bg {
  background: radial-gradient(circle at bottom, transparent 24%, #375625 25%, #375625 30%, transparent 31%, transparent 39%, #375625 40%, #375625 45%, transparent 46%), radial-gradient(circle at top, transparent 24%, #375625 25%, #375625 30%, transparent 31%, transparent 39%, #375625 40%, #375625 45%, transparent 46%), radial-gradient(circle at left, transparent 24%, #375625 25%, #375625 30%, transparent 31%, transparent 39%, #375625 40%, #375625 45%, transparent 46%), radial-gradient(circle at right, transparent 24%, #375625 25%, #375625 30%, transparent 31%, transparent 39%, #375625 40%, #375625 45%, transparent 46%);
  background-size: 1em 1em;
  background-color: #224840;
  opacity: 1;
} /* Courtesy https://superdesigner.co/tools/css-backgrounds */

ResumeDL {
  margin: 5px; 
}

/* DESKTOP VIEW */
@media screen and (min-width: 600px) {
  #main {
    align-items: center;
  }
  .content, #nav {
    width: 80%;
  }
  #nav a {
    flex: 1;
  }
  .p-wrapper {
    margin-bottom: .5rem;
  }
  p, ul {
    text-align: center;
  }
  .viewDesktop {
    display: unset !important;
  }
}
</style>


